### ISSUE TITLE
Review block architecture

### ISSUE THREAD

**Issue by nkaskov** [NilFoundation/block#18]
There is a lot of bugs and obsolete code in blocks's architecture.

**Comment by nkaskov** [comment]
Requires closing [the pack issue](https://github.com/NilFoundation/hash/issues/30).

**Comment by a1falcon** [comment]
For various types of processed data to be supported one needs to reconsider the structure of cipher_fixture. Vectors and strings, for example, require allocation, while for std::array type simple declaration will be sufficient.
